version: '3'
services:
  dbhost_1:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - "./datadir_primary:/data/db"
    command: mongod --replSet rs0 --bind_ip_all

  dbhost_2:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
        - "./datadir_secondary1:/data/db"
    command: mongod --replSet rs0 --bind_ip_all


  dbhost_3:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
        - "./datadir_secondary2:/data/db"
    command: mongod --replSet rs0 --bind_ip_all